version: '3.8'

services:
  db:
    container_name: mongodb
    image: mongo:latest
    ports:
      - '27017:27017'

  cache:
    stop_grace_period: 1s
    container_name: redis
    image: redis:7-alpine
    restart: unless-stopped
    volumes:
      - 'annotator_cache:/data'
    expose:
      - 6379
    command: ['redis-server', '--loglevel', 'warning']
    ports:
      - '6379:6379'

  api:
    container_name: api
    network_mode: 'host'
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./.env
    depends_on:
      - db
      - cache
    working_dir: /app
    volumes:
      - ./backend:/app
    command: sh -c "cargo watch -x run"
    expose:
      - 8080
    ports:
      - '8080:8080'

  app:
    container_name: webapp
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file:
      - ./.env
    working_dir: /app
    volumes:
      - ./frontend:/app
    depends_on:
      - api
    expose:
      - 3000
    ports:
      - '3000:3000'

volumes:
  annotator_cache:
